-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 19:56:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_asistencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_asistencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_asistencia` DEFAULT CHARACTER SET utf8 ;
USE `db_asistencia` ;

-- -----------------------------------------------------
-- Table `db_asistencia`.`tbl_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`tbl_alumno` (
  `alumno_id` INT NOT NULL AUTO_INCREMENT,
  `alumno_nombre` VARCHAR(255) NOT NULL,
  `alumno_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`alumno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`tbl_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`tbl_curso` (
  `curso_id` INT NOT NULL AUTO_INCREMENT,
  `curso_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`curso_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`tbl_asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`tbl_asistencia` (
  `asistencia_id` INT NOT NULL AUTO_INCREMENT,
  `asistencia_fecha` DATE NOT NULL,
  `asistencia_valor` SMALLINT(1) NOT NULL DEFAULT 1,
  `alumno_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  PRIMARY KEY (`asistencia_id`),
  CONSTRAINT `fk_tbl_asistencia_tbl_alumno`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db_asistencia`.`tbl_alumno` (`alumno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_asistencia_tbl_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `db_asistencia`.`tbl_curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
