-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 20:57:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_devhub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_devhub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_devhub` DEFAULT CHARACTER SET utf8 ;
USE `db_devhub` ;

-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_location` (
  `id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_job` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(200) NULL,
  `title` VARCHAR(200) NOT NULL,
  `salary` DOUBLE NOT NULL,
  `created_date` DATE NULL,
  `vacancies` INT NULL,
  `description` LONGTEXT NULL,
  `company_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `experience_year` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_job_tbl_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_devhub`.`tbl_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_job_tbl_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `db_devhub`.`tbl_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_job_tbl_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_devhub`.`tbl_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_job_tbl_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `db_devhub`.`tbl_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_job_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_job_skill` (
  `id` INT NOT NULL,
  `job_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_job_skill_tbl_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `db_devhub`.`tbl_job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_job_skill_tbl_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `db_devhub`.`tbl_skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_candidate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `image` VARCHAR(200) NULL,
  `title` VARCHAR(200) NOT NULL,
  `experience_year` INT NOT NULL,
  `location_id` INT NOT NULL,
  `resume` VARCHAR(255) NULL,
  `aboutme` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_candidate_tbl_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `db_devhub`.`tbl_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_candidate_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_candidate_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `candidate_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_candidate_skill_tbl_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `db_devhub`.`tbl_candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_candidate_skill_tbl_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `db_devhub`.`tbl_skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_candidate_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_candidate_experience` (
  `position` VARCHAR(200) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NULL,
  `candidate_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_candidate_experience_tbl_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `db_devhub`.`tbl_candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_candidate_experience_tbl_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_devhub`.`tbl_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_candidate_study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_candidate_study` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `school` VARCHAR(200) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` LONGTEXT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NULL,
  `candidate_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_candidate_study_tbl_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `db_devhub`.`tbl_candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_devhub`.`tbl_job_apply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_devhub`.`tbl_job_apply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_apply` DATE NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `job_id` INT NOT NULL,
  `candidate_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_job_apply_tbl_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `db_devhub`.`tbl_job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_job_apply_tbl_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `db_devhub`.`tbl_candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
