# Generated by Django 3.2 on 2023-10-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_cliente'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='tbl_cliente',
        ),
    ]
