version : '3.3'

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  api:
    build: .
    image: img-backend-api:1.0
    ports:
      - "5000:5000"
    environment:
      MONGOURI: mongodb://db/db_cursos
    depends_on:
      - db