# Generated by Django 3.2 on 2023-10-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_pedido'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='tbl_pedido',
        ),
    ]
