version: "3.3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=codigo
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"